language : node_js
node_js : "stable"
install : npm install
services:
  - postgresql
before_script:
  - psql -c 'create database yourvote;' -U postgres
script : npm test 
after_script : npm run coverage
