language : node_js
node_js : "stable"
env :
- KEYWORD=kjhdfkjhdfbnfddfkksdioufbrnbkjskhjsdjhks
- DATABASE_URL=postgresql://postgres:ally@localhost:5432/yourvote 
cache:
  directories:
    - node_modules
install : npm install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE yourvote;' -U postgres
script : npm test 
after_script : npm run coverage