language : node_js
node_js : "stable"
cache:
  directories:
    - node_modules
install : npm install
          travis_wait mvn install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE yourvote;' -U postgres
script : npm test 
after_script : npm run coverage